# Form implementation generated from reading ui file 'edit_entry.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 497)
        Dialog.setStyleSheet("font: 10pt \"Noto Sans SemiCondensed\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(172, 229, 238, 255), stop:1 rgba(204, 204, 255, 255))")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainFrame = QtWidgets.QFrame(parent=Dialog)
        self.mainFrame.setStyleSheet("background-color: rgba(255,255,255, 80);\n"
"border: 1px solid rgb(70,68,81);\n"
"color: rgb(70,68,81);\n"
"border-radius: 10;\n"
"font-size: 14pt;\n"
"")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newEntryLabel = QtWidgets.QLabel(parent=self.mainFrame)
        self.newEntryLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.newEntryLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.newEntryLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.newEntryLabel.setObjectName("newEntryLabel")
        self.verticalLayout.addWidget(self.newEntryLabel)
        self.descriptionLineEdit = QtWidgets.QLineEdit(parent=self.mainFrame)
        self.descriptionLineEdit.setStyleSheet("padding-left: 5")
        self.descriptionLineEdit.setInputMask("")
        self.descriptionLineEdit.setText("")
        self.descriptionLineEdit.setFrame(True)
        self.descriptionLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.descriptionLineEdit.setCursorPosition(0)
        self.descriptionLineEdit.setDragEnabled(False)
        self.descriptionLineEdit.setReadOnly(False)
        self.descriptionLineEdit.setClearButtonEnabled(False)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.verticalLayout.addWidget(self.descriptionLineEdit)
        self.priceSpinBox = QtWidgets.QSpinBox(parent=self.mainFrame)
        self.priceSpinBox.setStyleSheet("")
        self.priceSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.priceSpinBox.setMinimum(0)
        self.priceSpinBox.setMaximum(100000000)
        self.priceSpinBox.setProperty("value", 0)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.verticalLayout.addWidget(self.priceSpinBox)
        self.categoryComboBox = QtWidgets.QComboBox(parent=self.mainFrame)
        self.categoryComboBox.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.categoryComboBox.setStyleSheet("QComboBox {\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"}")
        self.categoryComboBox.setEditable(False)
        self.categoryComboBox.setDuplicatesEnabled(False)
        self.categoryComboBox.setFrame(True)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.verticalLayout.addWidget(self.categoryComboBox)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.mainFrame)
        self.dateEdit.setStyleSheet("border-radius: 5;")
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dateEdit.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.dateEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.saveButton = QtWidgets.QPushButton(parent=self.mainFrame)
        self.saveButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.saveButton.setStyleSheet("QPushButton { \n"
"background-color: rgba(255,255,255, 80);\n"
"border: 1px solid rgb(70,68,81);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255, 110);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255, 150);\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.verticalLayout_2.addWidget(self.mainFrame)

        self.retranslateUi(Dialog)
        self.categoryComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.newEntryLabel.setText(_translate("Dialog", "Изменение записи"))
        self.descriptionLineEdit.setPlaceholderText(_translate("Dialog", "Описание"))
        self.categoryComboBox.setCurrentText(_translate("Dialog", "Поступления"))
        self.categoryComboBox.setPlaceholderText(_translate("Dialog", "Категория"))
        self.categoryComboBox.setItemText(0, _translate("Dialog", "Поступления"))
        self.categoryComboBox.setItemText(1, _translate("Dialog", "Авиабилеты"))
        self.categoryComboBox.setItemText(2, _translate("Dialog", "Автоуслуги"))
        self.categoryComboBox.setItemText(3, _translate("Dialog", "Аптеки"))
        self.categoryComboBox.setItemText(4, _translate("Dialog", "Аренда авто"))
        self.categoryComboBox.setItemText(5, _translate("Dialog", "Благотворительность"))
        self.categoryComboBox.setItemText(6, _translate("Dialog", "Дом, ремонт"))
        self.categoryComboBox.setItemText(7, _translate("Dialog", "Ж/д билеты"))
        self.categoryComboBox.setItemText(8, _translate("Dialog", "Животные"))
        self.categoryComboBox.setItemText(9, _translate("Dialog", "Искусство"))
        self.categoryComboBox.setItemText(10, _translate("Dialog", "Кино"))
        self.categoryComboBox.setItemText(11, _translate("Dialog", "Красота"))
        self.categoryComboBox.setItemText(12, _translate("Dialog", "Медицинские услуги"))
        self.categoryComboBox.setItemText(13, _translate("Dialog", "Музыка"))
        self.categoryComboBox.setItemText(14, _translate("Dialog", "Образование"))
        self.categoryComboBox.setItemText(15, _translate("Dialog", "Одежда, обувь"))
        self.categoryComboBox.setItemText(16, _translate("Dialog", "Отели"))
        self.categoryComboBox.setItemText(17, _translate("Dialog", "Развлечения"))
        self.categoryComboBox.setItemText(18, _translate("Dialog", "Рестораны"))
        self.categoryComboBox.setItemText(19, _translate("Dialog", "Связь"))
        self.categoryComboBox.setItemText(20, _translate("Dialog", "Сервис-услуги"))
        self.categoryComboBox.setItemText(21, _translate("Dialog", "Спорттовары"))
        self.categoryComboBox.setItemText(22, _translate("Dialog", "Сувениры"))
        self.categoryComboBox.setItemText(23, _translate("Dialog", "Супермаркеты"))
        self.categoryComboBox.setItemText(24, _translate("Dialog", "Топливо"))
        self.categoryComboBox.setItemText(25, _translate("Dialog", "Транспорт"))
        self.categoryComboBox.setItemText(26, _translate("Dialog", "Фастфуд"))
        self.categoryComboBox.setItemText(27, _translate("Dialog", "Финансовые услуги"))
        self.categoryComboBox.setItemText(28, _translate("Dialog", "Фото/видео"))
        self.categoryComboBox.setItemText(29, _translate("Dialog", "Цветы"))
        self.categoryComboBox.setItemText(30, _translate("Dialog", "Частные услуги"))
        self.categoryComboBox.setItemText(31, _translate("Dialog", "Прочее"))
        self.saveButton.setText(_translate("Dialog", "Сохранить"))
