# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 659)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(974, 659))
        MainWindow.setMaximumSize(QtCore.QSize(974, 659))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        MainWindow.setStyleSheet("font: 10pt \"Noto Sans SemiCondensed\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(172, 229, 238, 255), stop:1 rgba(204, 204, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainHBox = QtWidgets.QHBoxLayout()
        self.mainHBox.setObjectName("mainHBox")
        self.balanceFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.balanceFrame.setMinimumSize(QtCore.QSize(310, 0))
        self.balanceFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.balanceFrame.setAutoFillBackground(False)
        self.balanceFrame.setStyleSheet("background-color: rgba(255,255,255, 80);\n"
"border: 1px solid rgb(70,68,81);\n"
"color: rgb(70,68,81);\n"
"border-radius: 10;\n"
"")
        self.balanceFrame.setObjectName("balanceFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.balanceFrame)
        self.verticalLayout_6.setContentsMargins(11, 20, -1, 50)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.balanceStaticHBox = QtWidgets.QHBoxLayout()
        self.balanceStaticHBox.setContentsMargins(0, -1, -1, -1)
        self.balanceStaticHBox.setObjectName("balanceStaticHBox")
        self.creditCardIconLabel = QtWidgets.QLabel(parent=self.balanceFrame)
        self.creditCardIconLabel.setMaximumSize(QtCore.QSize(40, 40))
        self.creditCardIconLabel.setStyleSheet("\n"
"background-color: none;\n"
"border: none")
        self.creditCardIconLabel.setText("")
        self.creditCardIconLabel.setPixmap(QtGui.QPixmap(":/icons/icons/credit_card_40dp.svg"))
        self.creditCardIconLabel.setScaledContents(True)
        self.creditCardIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.creditCardIconLabel.setWordWrap(False)
        self.creditCardIconLabel.setObjectName("creditCardIconLabel")
        self.balanceStaticHBox.addWidget(self.creditCardIconLabel)
        self.balanceStaticLabel = QtWidgets.QLabel(parent=self.balanceFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans SemiCondensed")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.balanceStaticLabel.setFont(font)
        self.balanceStaticLabel.setStyleSheet("font-weight: bold;\n"
"font-size: 24pt;\n"
"background-color: none;\n"
"border: none")
        self.balanceStaticLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.balanceStaticLabel.setObjectName("balanceStaticLabel")
        self.balanceStaticHBox.addWidget(self.balanceStaticLabel)
        self.verticalLayout_6.addLayout(self.balanceStaticHBox)
        self.balanceDynamicHBox = QtWidgets.QHBoxLayout()
        self.balanceDynamicHBox.setContentsMargins(0, -1, -1, -1)
        self.balanceDynamicHBox.setObjectName("balanceDynamicHBox")
        self.rubleIconLabel = QtWidgets.QLabel(parent=self.balanceFrame)
        self.rubleIconLabel.setMaximumSize(QtCore.QSize(30, 30))
        self.rubleIconLabel.setStyleSheet("background-color: none;\n"
"border: none")
        self.rubleIconLabel.setText("")
        self.rubleIconLabel.setPixmap(QtGui.QPixmap(":/icons/icons/currency_ruble_40dp.svg"))
        self.rubleIconLabel.setScaledContents(True)
        self.rubleIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.rubleIconLabel.setObjectName("rubleIconLabel")
        self.balanceDynamicHBox.addWidget(self.rubleIconLabel)
        self.balanceDynamicLabel = QtWidgets.QLabel(parent=self.balanceFrame)
        self.balanceDynamicLabel.setStyleSheet("font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none")
        self.balanceDynamicLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.balanceDynamicLabel.setObjectName("balanceDynamicLabel")
        self.balanceDynamicHBox.addWidget(self.balanceDynamicLabel)
        self.verticalLayout_6.addLayout(self.balanceDynamicHBox)
        self.mainHBox.addWidget(self.balanceFrame)
        self.filtersFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.filtersFrame.setStyleSheet("background-color: rgba(255,255,255, 80);\n"
"border: 1px solid rgb(70,68,81);\n"
"color: rgb(70,68,81);\n"
"border-radius: 10;")
        self.filtersFrame.setObjectName("filtersFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filtersFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filtersLabel = QtWidgets.QLabel(parent=self.filtersFrame)
        self.filtersLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.filtersLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"")
        self.filtersLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.filtersLabel.setObjectName("filtersLabel")
        self.verticalLayout.addWidget(self.filtersLabel)
        self.filtersHBox = QtWidgets.QHBoxLayout()
        self.filtersHBox.setObjectName("filtersHBox")
        self.dateFrame = QtWidgets.QFrame(parent=self.filtersFrame)
        self.dateFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.dateFrame.setStyleSheet("font-size: 14pt;")
        self.dateFrame.setObjectName("dateFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dateFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dateHBox = QtWidgets.QHBoxLayout()
        self.dateHBox.setObjectName("dateHBox")
        self.dateIconLabel = QtWidgets.QLabel(parent=self.dateFrame)
        self.dateIconLabel.setMaximumSize(QtCore.QSize(24, 16777215))
        self.dateIconLabel.setStyleSheet("background-color: none;\n"
"border: none")
        self.dateIconLabel.setText("")
        self.dateIconLabel.setPixmap(QtGui.QPixmap(":/icons/icons/calendar_today_24dp.svg"))
        self.dateIconLabel.setObjectName("dateIconLabel")
        self.dateHBox.addWidget(self.dateIconLabel)
        self.dateLabel = QtWidgets.QLabel(parent=self.dateFrame)
        self.dateLabel.setStyleSheet("font-weight: bold;\n"
"background-color: none;\n"
"border: none")
        self.dateLabel.setObjectName("dateLabel")
        self.dateHBox.addWidget(self.dateLabel)
        self.dateCheckBox = QtWidgets.QCheckBox(parent=self.dateFrame)
        self.dateCheckBox.setEnabled(True)
        self.dateCheckBox.setMinimumSize(QtCore.QSize(0, 0))
        self.dateCheckBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.dateCheckBox.setStyleSheet("\n"
"border: none")
        self.dateCheckBox.setChecked(True)
        self.dateCheckBox.setTristate(False)
        self.dateCheckBox.setObjectName("dateCheckBox")
        self.dateHBox.addWidget(self.dateCheckBox)
        self.verticalLayout_2.addLayout(self.dateHBox)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.dateFrame)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDateEdit:disabled {\n"
"    background-color: rgba(165,165,165,90);\n"
"    color: rgba(70,68,81,200);\n"
"}")
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dateEdit.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.dateEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_2.addWidget(self.dateEdit)
        self.filtersHBox.addWidget(self.dateFrame)
        self.categoryFrame = QtWidgets.QFrame(parent=self.filtersFrame)
        self.categoryFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.categoryFrame.setStyleSheet("font-size: 14pt;")
        self.categoryFrame.setObjectName("categoryFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.categoryFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.categoryHBox = QtWidgets.QHBoxLayout()
        self.categoryHBox.setObjectName("categoryHBox")
        self.categoryIconLabel = QtWidgets.QLabel(parent=self.categoryFrame)
        self.categoryIconLabel.setMaximumSize(QtCore.QSize(24, 16777215))
        self.categoryIconLabel.setStyleSheet("background-color: none;\n"
"border: none")
        self.categoryIconLabel.setText("")
        self.categoryIconLabel.setPixmap(QtGui.QPixmap(":/icons/icons/local_offer_24dp.svg"))
        self.categoryIconLabel.setScaledContents(False)
        self.categoryIconLabel.setObjectName("categoryIconLabel")
        self.categoryHBox.addWidget(self.categoryIconLabel)
        self.categoryLabel = QtWidgets.QLabel(parent=self.categoryFrame)
        self.categoryLabel.setStyleSheet("font-weight: bold;\n"
"background-color: none;\n"
"border: none")
        self.categoryLabel.setObjectName("categoryLabel")
        self.categoryHBox.addWidget(self.categoryLabel)
        self.categoryCheckBox = QtWidgets.QCheckBox(parent=self.categoryFrame)
        self.categoryCheckBox.setMinimumSize(QtCore.QSize(0, 0))
        self.categoryCheckBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.categoryCheckBox.setStyleSheet("border: none")
        self.categoryCheckBox.setChecked(True)
        self.categoryCheckBox.setObjectName("categoryCheckBox")
        self.categoryHBox.addWidget(self.categoryCheckBox)
        self.verticalLayout_4.addLayout(self.categoryHBox)
        self.categoryComboBox = QtWidgets.QComboBox(parent=self.categoryFrame)
        self.categoryComboBox.setEnabled(False)
        self.categoryComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.categoryComboBox.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.categoryComboBox.setStyleSheet("QComboBox {\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"    background-color: rgba(165,165,165,90);\n"
"    color: rgba(70,68,81,200);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:disabled {\n"
"    background-color: gray;\n"
"    color: lightgray;\n"
"}")
        self.categoryComboBox.setEditable(False)
        self.categoryComboBox.setCurrentText("")
        self.categoryComboBox.setDuplicatesEnabled(False)
        self.categoryComboBox.setFrame(True)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.categoryComboBox)
        self.filtersHBox.addWidget(self.categoryFrame)
        self.verticalLayout.addLayout(self.filtersHBox)
        self.mainHBox.addWidget(self.filtersFrame)
        self.verticalLayout_3.addLayout(self.mainHBox)
        self.buttonsFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.buttonsFrame.setStyleSheet("background-color: none;\n"
"color: rgb(70,68,81);\n"
"border-radius: 10;\n"
"font-size: 14pt;")
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addButton = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.addButton.setMinimumSize(QtCore.QSize(310, 0))
        self.addButton.setStyleSheet("QPushButton { \n"
"background-color: rgba(255,255,255, 80);\n"
"border: 1px solid rgb(70,68,81);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255, 110);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255, 150);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/post_add_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QtCore.QSize(30, 30))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.editButton.setMinimumSize(QtCore.QSize(310, 0))
        self.editButton.setStyleSheet("QPushButton { \n"
"background-color: rgba(255,255,255, 80);\n"
"border: 1px solid rgb(70,68,81);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255, 110);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255, 150);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.editButton.setIcon(icon1)
        self.editButton.setIconSize(QtCore.QSize(30, 30))
        self.editButton.setObjectName("editButton")
        self.horizontalLayout_2.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.deleteButton.setMinimumSize(QtCore.QSize(310, 0))
        self.deleteButton.setStyleSheet("QPushButton { \n"
"background-color: rgba(255,255,255, 80);\n"
"border: 1px solid rgb(70,68,81);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255, 110);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255, 150);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/delete_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.deleteButton.setIcon(icon2)
        self.deleteButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.verticalLayout_3.addWidget(self.buttonsFrame)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setStyleSheet("QTableView {\n"
"font-size: 14pt;\n"
"background-color: rgba(255, 255, 255, 80); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-bottom-right-radius: 7px; \n"
"border-bottom-left-radius: 7px; \n"
"color: rgb(70, 68, 81);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgba(255, 255, 255, 100);\n"
"color: rgb(70, 68, 81);\n"
"border: none;\n"
"height: 50px;\n"
"font-size: 16pt;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(70, 68, 81);\n"
"    padding-left: 5px;\n"
"    padding-right: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QTableView::item:selected{\n"
"    border: none;\n"
"    color: rgb(70, 68, 81);\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.tableView.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.tableView.setShowGrid(False)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.tableView.verticalHeader().setCascadingSectionResizes(True)
        self.tableView.verticalHeader().setMinimumSectionSize(20)
        self.tableView.verticalHeader().setSortIndicatorShown(True)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.categoryComboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Учет финансов"))
        self.balanceStaticLabel.setText(_translate("MainWindow", "Баланс"))
        self.balanceDynamicLabel.setText(_translate("MainWindow", "999999"))
        self.filtersLabel.setText(_translate("MainWindow", "Показать записи"))
        self.dateLabel.setText(_translate("MainWindow", "По дате"))
        self.dateCheckBox.setText(_translate("MainWindow", "Все"))
        self.categoryLabel.setText(_translate("MainWindow", "По категории"))
        self.categoryCheckBox.setText(_translate("MainWindow", "Все"))
        self.categoryComboBox.setPlaceholderText(_translate("MainWindow", "Категория"))
        self.categoryComboBox.setItemText(0, _translate("MainWindow", "Поступления"))
        self.categoryComboBox.setItemText(1, _translate("MainWindow", "Авиабилеты"))
        self.categoryComboBox.setItemText(2, _translate("MainWindow", "Автоуслуги"))
        self.categoryComboBox.setItemText(3, _translate("MainWindow", "Аптеки"))
        self.categoryComboBox.setItemText(4, _translate("MainWindow", "Аренда авто"))
        self.categoryComboBox.setItemText(5, _translate("MainWindow", "Благотворительность"))
        self.categoryComboBox.setItemText(6, _translate("MainWindow", "Дом, ремонт"))
        self.categoryComboBox.setItemText(7, _translate("MainWindow", "Ж/д билеты"))
        self.categoryComboBox.setItemText(8, _translate("MainWindow", "Животные"))
        self.categoryComboBox.setItemText(9, _translate("MainWindow", "Искусство"))
        self.categoryComboBox.setItemText(10, _translate("MainWindow", "Кино"))
        self.categoryComboBox.setItemText(11, _translate("MainWindow", "Красота"))
        self.categoryComboBox.setItemText(12, _translate("MainWindow", "Медицинские услуги"))
        self.categoryComboBox.setItemText(13, _translate("MainWindow", "Музыка"))
        self.categoryComboBox.setItemText(14, _translate("MainWindow", "Образование"))
        self.categoryComboBox.setItemText(15, _translate("MainWindow", "Одежда, обувь"))
        self.categoryComboBox.setItemText(16, _translate("MainWindow", "Отели"))
        self.categoryComboBox.setItemText(17, _translate("MainWindow", "Развлечения"))
        self.categoryComboBox.setItemText(18, _translate("MainWindow", "Рестораны"))
        self.categoryComboBox.setItemText(19, _translate("MainWindow", "Связь"))
        self.categoryComboBox.setItemText(20, _translate("MainWindow", "Сервис-услуги"))
        self.categoryComboBox.setItemText(21, _translate("MainWindow", "Спорттовары"))
        self.categoryComboBox.setItemText(22, _translate("MainWindow", "Сувениры"))
        self.categoryComboBox.setItemText(23, _translate("MainWindow", "Супермаркеты"))
        self.categoryComboBox.setItemText(24, _translate("MainWindow", "Топливо"))
        self.categoryComboBox.setItemText(25, _translate("MainWindow", "Транспорт"))
        self.categoryComboBox.setItemText(26, _translate("MainWindow", "Фастфуд"))
        self.categoryComboBox.setItemText(27, _translate("MainWindow", "Финансовые услуги"))
        self.categoryComboBox.setItemText(28, _translate("MainWindow", "Фото/видео"))
        self.categoryComboBox.setItemText(29, _translate("MainWindow", "Цветы"))
        self.categoryComboBox.setItemText(30, _translate("MainWindow", "Частные услуги"))
        self.categoryComboBox.setItemText(31, _translate("MainWindow", "Прочее"))
        self.addButton.setText(_translate("MainWindow", "Добавить запись"))
        self.editButton.setText(_translate("MainWindow", "Изменить запись"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить запись"))
